name: Anomaly_Classification
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - charset-normalizer
      - cycler
      - fonttools
      - idna
      - joblib
      - kiwisolver
      - matplotlib
      - numpy
      - opencv-python
      - packaging
      - pillow
      - pyparsing
      - python-dateutil
      - requests
      - scikit-learn
      - scipy
      - six
      - threadpoolctl
      - torch
      - torchvision
      - typing-extensions
      - urllib3